### ISSUE TITLE
import privkey for testnet failed

### ISSUE THREAD

**Issue by KStasi** [satoshipay/solar#1081]
<img width="801" alt="Screenshot 2020-05-12 at 14 36 37" src="https://user-images.githubusercontent.com/31795791/81682891-003c2600-945e-11ea-9130-8b152f09d3f8.png">
<img width="609" alt="Screenshot 2020-05-12 at 14 31 29" src="https://user-images.githubusercontent.com/31795791/81682892-00d4bc80-945e-11ea-93e8-830bc4477c10.png">

**Comment by andywer** [comment]
Hey @KStasi!

Sorry for the late reply. We have been super busy fixing the issue and preparing the upcoming release. The issue has been fixed by #1087 – it's due to the upgrade to the protocol version 13 of the testnet.

We are aiming for a release early next week, but maybe we can already share a build here before that.

/cc @DiyanDoychev
