### ISSUE TITLE
Electron exception when pressing update notification twice

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#1110]
As seen on Windows:
"I hit update in the notification and after a while, because nothing happened, again by pressing update next to the settings button above." (as reported by Alex)

It's of course also sub-optimal that the user cannot see the update progress.

![image](https://user-images.githubusercontent.com/1842462/86897071-3b2da380-c107-11ea-9ce9-a61ae2d837ab.png)

**Comment by ebma** [comment]
There is not much we can do about the update progress issue because the build-in electron `autoUpdater` does not offer subscribing to the download progress. The `electron-builder` one does but IIRC we had issues with that (and it had some security issues) so I would opt for not switching back to it. 

And in general the user should not be able to press the update button twice as long as he does not manually reload the page/app but we cannot prevent that because we cannot check if the update is already running (we can only listen to that error which is thrown after starting it twice).
