### ISSUE TITLE
Cannot read property 'available' of undefined AND Cannot read property 'name' of undefined 

### ISSUE THREAD

**Issue by CubeBank** [satoshipay/solar#1135]
Hello guys, I'm trying to run the installation, from the wallet, with the following commands.
after compilation, when I try to create or import an account the errors below appear.
Any idea? How do I solve this?
My O.S
((Linux Manjaro 5.4.44-1-MANJARO # 1 SMP PREEMPT Wed Jun 3 14:48:07 UTC 2020 x86_64 GNU / Linux))

  installation of the solar wallet.

git clone https://github.com/satoshipay/solar.git
solar cd /
npm install
cd cordova /
npm install --save stellar-sdk
npm install
npm run install: android
npm run dev: android

Any idea? How do I solve this?

![Screenshot_20200814_151206](https://user-images.githubusercontent.com/61805287/90279976-893d7180-de40-11ea-83a5-3553fb509e4b.png)

![Screenshot_20200814_151307](https://user-images.githubusercontent.com/61805287/90280056-abcf8a80-de40-11ea-8c67-3ca988203e34.png)

**Comment by ebma** [comment]
Hey @CubeBank, you are encountering these issues because when you run `npm run dev:android` the application expects to be run in an android environment. Since the cordova plugins are not available in your web browser these errors are thrown. 
So you have to options: 
1. If you want to run the development build in your web browser navigate to the `web/` directory and run `npm run dev` (see [here](https://github.com/satoshipay/solar#run-dev-server-without-electron)).
2. If you want to run the development build on android you can launch android studio and run the application on an emulator. When importing the project to android studio it might help if you select 'Open an existing Android Studio project' and then select the `solar/platforms/android` directory as project root. Afterwards make sure to choose an emulator running an API version below 28 because you would encounter an error regarding cleartext network traffic otherwise.

In general it is easier to use the first approach. Running the development build on android makes sense if you want to test something platform specific or the cordova plugins.
