### ISSUE TITLE
Character limit in the MEMO field?

### ISSUE THREAD

**Issue by ZellarForum** [satoshipay/solar#1266]
Only 28 characters are available for input. However, some asset transactions (such as yXLM withdrawal in this particular case) require a memo consisting of more characters. This was a request to input a memo of 64 characters long, but it was not possible to enter due to the character limit. How could one proceed in this case with an incomplete memo for the transaction? Thank you.

**Comment by ebma** [comment]
Hello @ZellarForum, sorry for the late reply. Solar restricts you to 28 characters because Stellar puts this limitation on text memos, see [here](https://developers.stellar.org/docs/glossary/transactions/#memo). 
I honestly don't know how you are supposed to enter a 64 character memo, it just doesn't work. Maybe you can reach out to the asset issuer that requires such long memos and ask them what exactly they want you to do?

**Comment by ZellarForum** [comment]
Thank you for answering. I was unaware of such limitations on the network, so I apologize for asking about an unrelated to the wallet issue. I'll do as you advised.
