### ISSUE TITLE
Research how to securely store keys with Cordova

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#380]
Check the Cordova docs, google, check out other mobile wallet apps built with the same / a similar tech stack.

**Comment by Marcel-Ebert** [comment]
Cordova ships a plugin for file handling (see [Cordova File Plugin](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/))

The cordova.file object provides different options to access directories in a platform-independent way

The `cordova.file.dataDirectory` seems to be the go-to solution because it is readable + writable, persistent, not synced (e.g. with iTunes/iCloud) and application-private

**Comment by Marcel-Ebert** [comment]
Cordova plugin for securely storing secrets: [SecureStorage plugin for Apache Cordova
](https://github.com/crypho/cordova-plugin-secure-storage)

On iOS:
- Uses the KeyChain to store secrets

On Android:
- Uses AES and RSA to secure secrets
- RSA keypair is stored in Android Keystore
- AES key is secured with RSA and stored in SharedPreferences
- Users must have a secure screen-lock set

Android keystore might get deleted on security setting change (e.g. changing lock screen type):
"This means that any values saved using the plugin could be lost if the user changes security settings. The plugin should therefore be used as a secure credential cache and not persistent storage on Android."

But [Google Issue 'AndroidKeyStore deleted after changing screen lock type'](https://issuetracker.google.com/issues/36983155#comment35) and [Google Issue 'KeyStore Keys easily lost with poor UX'](https://issuetracker.google.com/issues/37099642#comment5) states that this should have been fixed since Android Marshmallow (Android 6.0).

**Comment by Marcel-Ebert** [comment]
Stargazer uses [sjcl](https://github.com/bitwiseshiftleft/sjcl) for encryption/decryption of stellar secret seeds.
The secured values are stored in and retrieved from `window.localStorage`. 

(see [storage.js](https://github.com/future-tense/stargazer/blob/master/app/core/services/storage.js), [keychain.js](https://github.com/future-tense/stargazer/blob/master/app/core/services/keychain.js) and [crypto.js](https://github.com/future-tense/stargazer/blob/master/app/core/services/crypto.js))

**Comment by andywer** [comment]
Will talk to @erasmus about the Android version support implications, but let's assume for now we are going to use the secure storage plugin.

**Comment by Marcel-Ebert** [comment]
Compare benefits of 1 key in secure storage vs separate entry for every key

**Comment by andywer** [comment]
As you showed me, it seems to be a fairly common pattern to dump a bunch of secrets into one key entry. Let's keep it lean and do the same.

**Comment by andywer** [comment]
We have a secure implementation now. Works on iOS and Android 5+.
