### ISSUE TITLE
IPC communication instead of webview access to cordova

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#384]
Ideally, we want our web view not to be able to access any platform features directly. Check if / how that's possible.

**Comment by andywer** [comment]
Let's do it timeboxed (30 mins or so) for now:

Is there a good solution for process isolation / message passing (IPC) for Cordova?

**Comment by Marcel-Ebert** [comment]
Nothing specific can be found for cordova in connection with IPC/message passing.

Regarding the iFrame approach [there is a security remark](https://cordova.apache.org/docs/en/8.x/guide/appdev/security/index.html#iframes-and-the-callback-id-mechanism) because the iFrame could gain access to the cordova native bridge and thus might be able to perform malicious actions.

**Comment by andywer** [comment]
In this case we definitely go for the sandboxed iFrame & `window.postMessage()`. InAppBrowser looks quite dead, at least regarding the features that we are interested in...

We just need to make sure that the iFrame also does not have access to the Cordova runtime in the production build (see #381).
