### ISSUE TITLE
Restrict IPC message handling on mobile

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#500]
Check if the sending frame is authorized to request this action.

**Comment by Marcel-Ebert** [comment]
Option 1:
Check if the origin of the sender can be trusted by comparing the origin of the received message-event with the one that is expected.

Does not work because the events passed via `postMessage()` currently have `origin: "null"` which might be due to the fact that the mainframe and iframe are considered as cross-origin frames because they are loaded from local files ([Explanation of same-origin policy for local files](https://developer.mozilla.org/en-US/docs/Archive/Misc_top_level/Same-origin_policy_for_file:_URIs)). 
Since the origin is "null" in both directions we can't tell if the message-origin is authorized to request a particular action. 


Alternative options..?

**Comment by andywer** [comment]
I think there is an alternative: There are two ways to check where the message was sent from - the `origin` and the `source` property of the event.

We should be able to compare `event.source === iframe.contentwindow` or similar. See <https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent/source>.
