### ISSUE TITLE
Clean up deps

### ISSUE THREAD

**Issue by Levino** [satoshipay/solar#671]
`react-router-dom` (and others) are declared `devDependencies` but used as `dependencies`.

https://github.com/satoshipay/solar/blob/aab24ea4d2bf1fe153504389fed2b55e52639c17/src/app.tsx#L5

https://github.com/satoshipay/solar/blob/c5bf86d73fefc6628b3ae0ea7d42ad83fbbbc87c/package.json#L63-L105

**Comment by andywer** [comment]
Hey Levin!

Well, this is super non-obvious, but as we cannot leave comments in JSON I will just explain it here.

Since this app is an electron app (among other things), any dependency that goes into `dependencies` will be packed into the electron app as-is, so it's available to the node runtime when the app runs.

We have a two-layer approach here, though: We have some code (not much) that is run in node.js and the React.js web front-end that we build and bundle to static assets. All the runtime dependencies of the node.js code must of course be in the `dependencies`.

All the runtime dependencies of the React app don't need to, though, as we bundle the whole React app at build time, so the React runtime dependencies are already included in the static bundle. Putting those dependencies in `dependencies` would ship them twice - once bundled into the bundle and once as-is in the electron runtime ASAR archive, thus increasing the resulting app's size.

**You have a point however, as there are dependencies in `dependencies` that are only ever used in the React code. We should move them to `devDependencies`.**

Maybe we should add a `CONTRIBUTION.md` and document things like that there?

**Comment by Levino** [comment]
My suggestion: Make it a lerna monorepo with one package for the React App and one package for bundling it in electron.

**Comment by Levino** [comment]
Maybe you could use https://github.com/electron-userland/electron-webpack when bundling for production which would shake out any unneeded deps.

**Comment by Levino** [comment]
Also what is the bundle size if you just include all the deps? It is to be downloaded on desktop anyhow, so not much trouble. I guess it should not be more than 500kb extra, but who knows_

**Comment by Levino** [comment]
Misclick
