### ISSUE TITLE
Make trading order creation wording consistent

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#789]
Right now the trading view main action button is labelled "Place order" while the transaction summary shows "Create trade offer". Review both wordings and make it consistent.

Look into "order" vs "offer" wording, too.

**Comment by Marcel-Ebert** [comment]
The labelling of the main action button and the transaction summary title is consistent already ("order" is used instead of "offer").

But I noticed that the headline above the list of open orders in the account page is "Open offers" and not "Open orders".

Furthermore, when looking into the source code there are many occurrences of "offer" (in variables as well as strings) that we might want to replace with "order"?
I'm not 100% sure to what extend we want to make this consistent e.g. if we want to change variable names as well or just care about strings etc.

**Comment by andywer** [comment]
Good point. Let's change the heading to "Open orders" and change the identifiers in the code over time.
