### ISSUE TITLE
Use Android app bundles (?)

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#852]
We talked about it earlier this year. Let’s have another look at it and discuss.
@Marcel-Ebert 

Could reduce APK size by about 20%. See <https://developer.android.com/topic/performance/reduce-apk-size#app_bundle>.

**Comment by Marcel-Ebert** [comment]
We have to use Googles 'App signing' mechanism in order to use .aab files to share our application (as Google will sign the bundle for us).
Since we don't use Googles App signing as of now and we don't have much benefits since our .apk file is super small anyways I'd suggest we just ignore the warning for now.
If it ever becomes obligatory we can still decide to opt in for the app signing and all we have to do to produce Android app bundles (.aab) is adding `--packageType=bundle` to the `build:android:signed` npm script.
